services:
  heiter:
    build:
      dockerfile: Dockerfile
      context: ./app

    env_file:
      - .env

    volumes:
      - ./app:/app  
      
    ports:
      - "8080:80"
    networks:
      - backend_network

    restart: unless-stopped

  redis:
    image: redis:8.6-alpine

    volumes:
      - redis_data:/data

    networks:
      - backend_network

    restart: unless-stopped

  postgres:
    image: postgres:18.1 
    env_file:
      - .env

    networks:
      - backend_network

    volumes:
      - postgres_data:/var/lib/postgresql/pgdata 
    restart: unless-stopped 

networks:
  backend_network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
